stevearc/aerial.nvim

lua/aerial/window.lua

There is currently an issue generating error `Cursor position outside buffer` in `aerial/window.lua:278` when using a global aerial window and switching to other windows.
When the cursor moves to another buffer, the last position that was selected for the aerial window is set. When the cursor previously was in a window with fewer symbols, this causes the line to not exist because symbols may publish after `CursorMoved` is triggered.
This fix checks if the line of the last selected symbol and line exists before jumping to it. The correct line will be selected when the symbols for the current buffer are rendered and the cursor moves.

Check if line exists before setting cursor

---

lua/aerial/data.lua

I use Aerial purely for quick navigation with code folding functionality disabled. I tend to call `require("aerial").tree_close_all()` quite a lot. Seeing all the root nodes as being folded is a bit disorienting.
Calling `tree_close_all` with this change:
Without:
This PR is just a proposal. If it doesn't suit Aerial's design, feel free to close it.

Fold empty root nodes only if `manage_folds` is enabled

---

README.md
doc/aerial.txt
doc/tags
lua/aerial/backends/init.lua
lua/aerial/backends/markdown.lua
lua/aerial/backends/treesitter/init.lua
lua/aerial/backends/util.lua
lua/aerial/config.lua
tests/markdown_spec.lua
tests/markdown_test.md
tests/test_util.lua
tests/treesitter/c_spec.lua
tests/treesitter/cpp_spec.lua
tests/treesitter/csharp_spec.lua
tests/treesitter/go_spec.lua
tests/treesitter/java_spec.lua
tests/treesitter/json_spec.lua
tests/treesitter/lua_spec.lua
tests/treesitter/python_spec.lua
tests/treesitter/rst_spec.lua
tests/treesitter/rust_spec.lua
tests/treesitter/ts_spec.lua
tests/treesitter/vim_spec.lua

Since we don't currently have a markdown parser for treesitter, this is a simple backend that should suffice for pulling out the headers.

Add support for markdown files

---

lua/aerial/config.lua
lua/aerial/navigation.lua

This PR adds the ability to configure aerial to automatically close the window upon selecting/jumping to a symbol. Please note that vimdocs will need to be generated for this :))

feat: added option to automatically close aerial on select (close_on_select)

---

lua/lualine/components/aerial.lua

Lualine is a widely used NeoVim statusline plugin. This patch adds a
lualine component that renders current symbol. It supports two rendering
modes:
1. When `hierarchy` is set to `true`, it renders the whole path to the
current symbol including parent nodes.
2. Otherwise, it renders the current symbol only.
The component also respects `icons_enabled` option that can turn on/off
symbol icons rendering.

Add lualine component to render current symbol

---

README.md
doc/aerial.txt
lua/aerial/autocommands.lua
lua/aerial/config.lua
lua/aerial/util.lua
lua/aerial/window.lua

Hi! Thank you for this wonderful plugin, it's been a great addition to my workflow.
This PR adds options to configure aerial to ignore certain windows/buffers. Ignored windows/buffers change the behavior of aerial as follows:
- If `close_behavior` is `"global"`, focusing an ignored window/buffer will not cause the aerial window to update.
- If `open_automatic` is `true`, focusing an ignored window/buffer will not cause an aerial window to open.
- If `open_automatic` is a function, ignore rules have no effect on aerial window opening behavior; it's handled by the `open_automatic` function.
The primary reason I made these changes is that when `close_behavior` is `"global"`, focusing a special window like [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) caused the aerial window to …

Add 'ignore' configuration options

---

README.md

Hi @stevearc,
Nice plugin :) I was originally trying to overwrite the key-bindings with the commands listed in the README, specifically replace `<CR>` to open the currently selected node in the AerialTree.
However there is no command I can see for this and I needed to see what the default bindings were doing. This just adds an extra link as the information of what to overwrite default bindings with seems to be missing.
Best,
Eddie

Add: Link to default bindings in README.md

---

README.md
lua/aerial/highlight.lua
lua/aerial/render.lua

Adds a highlight group `AerialLineNC` which is applied to the portion of a split line highlight for the non-current window. Requires `highlight_mode="split_width"` to have any effect.
By default, `AerialLineNC` is linked to `AerialLine`, so users will not notice a difference from prior behavior unless they define their own `AerialLineNC` highlight group.
I chose the `NC` name because it seems to be the convention used by vim for highlights relating to non-current windows, for example [`:help hl-StatusLineNC`](https://neovim.io/doc/user/syntax.html#hl-StatusLineNC).
https://user-images.githubusercontent.com/21299126/159594894-978f6e85-fafd-4016-b5ae-0864d00e6f76.mp4

feat: highlight group for non-current split line

---

lua/aerial/util.lua

Fixes https://github.com/stevearc/aerial.nvim/issues/76.

🐛 Don't crash on missing winid

---

README.md
lua/aerial/backends/treesitter/language_kind_map.lua
queries/org/aerial.scm
tests/init.lua
tests/treesitter/org_spec.lua
tests/treesitter/org_test.org

Hello and thank you for the great plugin. 
I needed an overview for long `org` files hence this pull request. In principle, this acts similarly to the markdown feature, showing headlines in the specified pane:
This uses the [tree-sitter-org](https://github.com/milisims/tree-sitter-org) parser, which isn't yet part of the nvim-treesitter repo.
I also ran the tests script and got errors for `markdown` and `org` which seems to be an issue with the `nvim-treesitter` plugin not properly recognizing custom parsers. Adding the line `vim.cmd([[runtime! plugin/orgmode.vim]])` (i.e. using the [orgmode](https://github.com/nvim-orgmode/orgmode) plugin) to the [tests/init.lua](https://github.com/stevearc/aerial.nvim/blob/3c64c5b76f2f09e23b91fd7c1dc29a6e0b953e68/tests/init.lua) file fixed the issue for …

feat: add support for org files

---

lua/aerial/window.lua

Set a name for Aerial buffer
This is useful for
- statuslines to display name
- plugins using buffer names (e.g. `nvim-web-devicons` to display an icon along buffer name)

fix: set buffer name after it's created

---

lua/aerial/backends/lsp/callbacks.lua
lua/aerial/backends/lsp/init.lua

```
[LSP] Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol
```
https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

fix: use server_capabilities instead of resolved_capabilities

---

lua/aerial/backends/treesitter/language_kind_map.lua
queries/teal/aerial.scm
tests/treesitter/teal_spec.lua
tests/treesitter/teal_test.tl

Thanks for great plugin! This PR adds [teal](https://github.com/teal-language/tl) (a typed dialect of Lua) language support. It's treesitter queries are analogous to Lua's.

feat(queries): add teal support

---

lua/aerial/backends/treesitter/language_kind_map.lua
queries/yaml/aerial.scm
tests/treesitter/yaml_spec.lua
tests/treesitter/yaml_test.yml

This PR adds basic support for YAML mappings and sequences.
In aerial window it looks nice:
..but in Telescope picker it is not ideal and difficult to search large files:
Seems it would be nice if `value` column contained full key path (e.g. `services.proxy.ports`, for example [yaml.nvim](https://github.com/cuducos/yaml.nvim) plugin does something like that), but I am not sure how to do that correctly or if it's in the scope of this plugin.

feat(queries): add basic yaml support

---

lua/aerial/navigation.lua

When `close_on_select` is set to true,  
aerial gets closed even when trying to preview the symbol definition with `}`, `{`, or `p`.  
Not very useful when just browsing through code using aerial,  
as this makes it impossible to actually "preview" the symbol definition.  
I think this option would be much more useful if it only closes aerial on "jump".  
(`<CR>`, `<C-v>`, `<C-s>`)

close_on_select should not close aerial on preview

---

lua/aerial/backends/treesitter/language_kind_map.lua
queries/scala/aerial.scm
tests/treesitter/scala_spec.lua
tests/treesitter/scala_test.scala

Adding basic support for the Scala language, solving https://github.com/stevearc/aerial.nvim/issues/139. It can potentially be extended, as this version only supports traits, objects, classes, and functions.

Add basic Scala treesitter support

---

README.md
doc/aerial.txt
doc/tags
lua/aerial/autocommands.lua
lua/aerial/backends/init.lua
lua/aerial/config.lua
lua/aerial/init.lua
lua/aerial/render.lua
lua/aerial/util.lua
lua/aerial/window.lua
tests/config_spec.lua

closes #128
Splits `close_behavior` into two new options: `attach_mode` and `close_automatic_events`. Also includes a complete rewrite of the logic that handles updating/autoclosing aerial windows, so it's quite possible some bugs slipped through.

Refactor close_behavior

---

lua/lualine/components/aerial.lua

Lualine already reacts to colorscheme changes and regenerates all highlight groups. Aerial routine ends up creating unnecessary highlight groups, eventually exhausting the highlight groups limit (a few colorscheme or background changes is all it takes).
This commit removes ColorScheme auto command, letting lualine do its own private magic.
Test command: `:filter /lualine_c_aerial_FileIcon/ hi`
Before:
```
lualine_c_aerial_FileIcon_normal xxx guifg=#d7827e guibg=#faf4ed                                                                                                                                                                
lualine_c_aerial_FileIcon_insert xxx guifg=#d7827e guibg=#faf4ed …
```

Let lualine deal with colorscheme

---

lua/lualine/components/aerial.lua

The following code makes lualine component crash because the symbol name contains '%'.
After this commit it should work.

fix: escape % in lualine component

---

lua/telescope/_extensions/aerial.lua

Hi! Great plugin!
I'd be interested in some extra customization for the telescope integration... In general telescope allows most things to be customizable through the opts parameter.
I've tried to make the entire make_entry customizable, but then it pulled half of the integration in my config file, because it pulls in make_display, displayer and so on.
So for now I came up with this simple approach, which is maybe not powerful enough (with this granular way, there may be a need for further integration points).
A way to make it more extensible without multiple extension points would be to use less local functions, but I understand you do that to achieve lazy loading, so I don't have any better idea..
As for the local modifications I'd like to achieve with these extension points: width 2 …

extra options for the telescope integration

---

README.md

Appreciate for your convenient plugin!
When testing your example code to customize lualine, I found that the original code of ``lualine_y`` leaded to a warning after restarting neovim. It says: 
```
lualine: There are some issues with your config. Run :LualineNotices for details
```
According to the hints in ``LualineNotices``, it turns out that another pair of curly braces is required. So I add these two braces for new comers like me in this PR.

fix Lualine customize example in README.md

---

README.md
doc/aerial.txt
lua/aerial/config.lua
lua/aerial/util.lua

Man pages are no longer ignored when `ignore.buftypes = "special"`.  
Allowing Aerial windows to be opened in the man pages by default.  
Aerial works beautifully well in the man pages, by the way.  
It would be a huge waste to disable this by default.

fix: aerial shouldn't be disabled by default in the man pages

---

lua/aerial/backends/init.lua
lua/aerial/backends/lsp/callbacks.lua
lua/aerial/util.lua
lua/aerial/window.lua

Buffer may have been :bwipeout-ed by user before the callback runs.
For example, I once ran into this error:
```
Error executing vim.schedule lua callback: ...lugged/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:46: Invalid buffer id: 39
stack traceback:
[C]: in function 'nvim_buf_line_count'
...lugged/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:46: in function 'process_symbols'
...lugged/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:136: in function 'handle_symbols'
...lugged/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:180: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

fix: check validity of buffer in deferred callbacks

---

lua/telescope/_extensions/aerial.lua

Hey, thanks for the plugin, it's great. One small feature I wanted was the option to not display lines in the telescope extension. This PR adds a new config option, `show_lines`:
```
require('telescope').setup({
...
extensions = {
aerial = {
show_lines = false,
}
}
})

Added an option to the telescope extension to hide lines

---

.gitmodules

Uses relative url for submodule so to enable users to clone from mirror site with `--recurse-submodules`.
Tested in  a site without GitHub access, using a mirror site
Tested with a normal configuration, using https://github.com as usual
Uses 2 levels of indirection (../../stevearc/nvim_doc_tools) instead of one (../nvim_doc_tools) so that people who fork aerial are not also forced to fork nvim_doc_tools.

fix: use relative url for submodule definition (#264)

---

README.md
doc/aerial.txt
lua/aerial/autocommands.lua
lua/aerial/config.lua
lua/aerial/render.lua
lua/aerial/util.lua
lua/aerial/window.lua

closes #267 
This adds a new config option `layout.resize_to_content` that, when false, prevents the aerial sidebar from updating its width to grow/shrink when the length of the symbols changes.

feat: add layout.resize_to_content config option

---

queries/elixir/aerial.scm
tests/treesitter/elixir_spec.lua
tests/treesitter/elixir_test.exs

it turns out elixir allows to skip the brackets for parameterless functions: aerial didn't take such functions into account so far.

elixir: support parameterless functions

---

lua/aerial/backends/treesitter/extensions.lua
queries/javascript/aerial.scm
queries/tsx/aerial.scm
queries/typescript/aerial.scm
tests/treesitter/js_spec.lua
tests/treesitter/js_test.js
tests/treesitter/ts_spec.lua
tests/treesitter/ts_test.ts
tests/treesitter/tsx_spec.lua
tests/treesitter/tsx_test.tsx

Treat JavaScript generator expressions as functions declarations.

fix: add JS / TS / TSX generator functions

---

lua/aerial/render.lua

I noticed that aerial highlight lines were not always correctly rendered. Especially when using edgy, that resizes component windows automatically.
Looking at the code, I found that to make a line, you used to pad with spaces, but this is not ideal.
Extmarks can be used instead that can extend to the EOL similar to the cursor line.
This PR implements that.
All the `highlight_modes` should work the same as before, but will now always properly extend till the end of the window when needed.

fix(render): use EOL extmarks to render AerialLine

---

lua/lualine/components/aerial.lua

Small PR to allow customizing the separator between the icon and the symbol.
Default separator is `" "` as before.
I personally prefer to set `sep = " "` and then `sep_icon = ""`.

feat(lualine): added `sep_icon` option

---

lua/telescope/_extensions/aerial.lua

results in telescope are reversed to show them in order as they appear in the document.
However, this doesn't work properly when `defaults.sorting_strategy = "ascending"`.
In that case, the table should not be reversed.
`aerial_picker` should be on top

feat(telescope): only reverse results when `sorting_strategy = "descending"`

---

lua/aerial/backends/treesitter/init.lua
queries/ruby/aerial.scm
tests/symbols/ruby_test.json
tests/treesitter/ruby_test.rb

This has direct impact on highlighting. If scope is set and set to anything but "public", highlighter will use a separate highlight for the corresponding entry. This was previously used by Elixir extension by manually processing nodes.
Elixir extension processing is removed, its queries updated, and fixed to consider not just `defp`, but also `defguardp` and `defmacrop` as private.
Ruby queries are updated to deal with both predicate and statement versions of scope setting. The query is kinda brittle still, as anything unexpected in between methods definitions will break it. "Not" match would solve the problem, but treesitter doesn't provide one. A custom predicate might be a way to go, but better is the enemy of good, so I'm stopping here.

Allow setting [privacy] scope from queries

---

.github/workflows/tests.yml
README.md
queries/objdump/aerial.scm
tests/minimal_init.lua
tests/symbols/objdump_test.json
tests/treesitter/objdump_test.objdump

Now that https://github.com/neovim/neovim/pull/23608 and https://github.com/nvim-treesitter/nvim-treesitter/commit/0179a89656b4ce395a4487c07ae385b8425524ae merged, objdump files are recognized in Neovim with tree-sitter support. Adding to aerial.nvim as well.
Since objdump files aren't really code, I wasn't sure what the preferred header would be. So I just chose `"Interface"` and `"Function"`. Open to suggestions, there.

Added aerial queries for objdump

---

run_tests.sh
tests/minimal_init.lua
tests/navigation_spec.lua
tests/symbols/markdown_test.json
tests/symbols/ruby_test.json

Recent update to nvim-treesitter breaks aerial.nvim tests.
Specifically:
- https://github.com/nvim-treesitter/nvim-treesitter/commit/96f55f30433
- https://github.com/MDeiml/tree-sitter-markdown/commit/cd705f15912
Prior version held a bunch of data written by hand. This commit updates
it to avoid false alarms when generating symbols for new or updated
queries.
Expectations are not changed, only the order of keys in individual
tables was updated.
While nvim-treesitter is not a strict requirement for aerial.nvim, it
is used to install parsers and it updates nvim default language to
parser assignments with practical values. This commit adds an ability to
run tests against `main` branch by providing `--test-main` option to
`run_tests.sh`.

Chores: Update markdown expectations, regenerate ruby symbols, enable nvim-treesitter main testing

---

README.md
doc/aerial.txt
lua/aerial/backends/treesitter/extensions.lua
lua/aerial/backends/treesitter/init.lua
queries/ruby/aerial.scm
tests/symbols/ruby_test.json

This lets us avoid complex querying when extracting scope.
As long as the capture includes a scoping node in a `@scope` capture, its text will be extracted and used as a scope value.
If "public" is named differently in some language, `#set @scope "text" "public"` will do the trick for a cost of maybe an additional query.
Ruby queries got condenced and cleaned up, which was the primary motivation for this PR.
PS: I'd split implementation and documentation into separate commits for ease of cherry-picking.

Process @scope captures and add basic query documentation

---

README.md
doc/aerial.txt
doc/api.md
lua/aerial/backends/treesitter/helpers.lua
lua/aerial/init.lua

When moving away from nvim-treesitter helpers, I overlooked the caching they were performing. This means that currently on every symbols refetch, neovim scans filesystem and gets all queries. Definitely useful when writing new queries, but slow nonetheless.
This commit introduces a simple query cache and an API method to clear said cache. With this, performance should improve, yet a way to iterate over query design remains accessible.

Cache aerial tree-sitter queries

---

autoload/aerial.vim

Remove extra double quotes around the fzf prompt which seems to be unecessary.
Without this fix merged the fzf prompt looks like this
With this fix merged the fzf prompt will look something like this without double quotes

fix: remove extra double quotes for fzf prompt

---

lua/telescope/_extensions/aerial.lua

NOTE: This PR is DIFFERENT from https://github.com/stevearc/aerial.nvim/pull/305 - this PR touches the **telescope extension**.
Suppose my cursor is on line 24, and then I open the aerial telescope window.
Then I select a symbol and jump to it.
If I press `Ctrl + o`, then I want to jump back to line 24.
This PR implements this feature.
Tested locally, and it works well for me!

feat(telescope): Save position into jumplist before 'edit' action

---

lua/aerial/window.lua

When opening nvim in diffview (`nvim -c DiffviewOpen`) and then toggeling aerial, aerial errors when trying to call `vim.api.nvim_win_is_valid(bufdata.last_win)` as bufdata.last_win == nil. This change adds a check and returns in case of a nil value.

check if bufdata.last_win != nil

---

queries/zig/aerial.scm
tests/symbols/zig_test.json
tests/treesitter/zig_test.zig

This is very basic level support but it's enough for me personally to get value out of this plugin while doing zig development.
I tried to have it differentiate between methods and functions but it would end up dropping structs which contain methods.

Add basic support for navigating zig files.

---

queries/julia/aerial.scm
tests/symbols/julia_test.json

This fixes the Julia queries to handle the breaking changes upstream.
This also fixes the symbol names to match what the language server returns. With Julia and it's multiple dispatch system it's very important to have the entire function definition in the symbol name. so we return the entire call expression as the `@name`
Fixes #361

fix(julia): treesitter queries changed upstream

---

lua/aerial/window.lua

The `nvim-0.5` branch should not have the deprecation warning for neovim versions smaller than `nvim-0.8`. This warning is for the `master` branch which requires newer neovim.

Remove deprecation warning in the nvim-0.5 branch

---

README.md
doc/aerial.txt
lua/aerial/config.lua
tests/config_spec.lua

This adds explicit support for [`mini.icons`](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-icons.md) for providing icons to oil. This generalizes the icon providing into a function that figures out which icon provider is available (preferring `mini.icons` over `lspkind`) and returning a common icon providing interface.
This also uses the `glyph` style in `mini.icons` to control the `nerd_font = "auto"` option since `mini.icons` has a built in style for not using nerd fonts and using plain text.
Lastly, this makes sure that the generalized icon provider function is lazily evaluated when it's necessary rather than on setup and caches the value so that it doesn't have to re-calculate the provider each time.

feat: add support for `mini.icons`

---

README.md
lua/telescope/_extensions/aerial.lua

Adds syntax highlighting in the telescope picker. Issue https://github.com/stevearc/aerial.nvim/issues/384
1. syntax highlighting is shown in the telescope picker. By Treesitter, so all supported languages work.
2. adds `only_lines` picker config to show only code w/o symbols.
3. fixes several minor bugs where override configs were not applied correctly.
Some results:
with `only_lines=true`
Other notes:
- `only_lines` - tried to name it in existing naming syntax, no any preferences, up to you
- this PR doesn't add syntax highlighting everywhere, which is a bigger task
- this PR doesn't solve all config issues, just some patches. Basically, IMO, all telescope configs need to be refactored to correctly pick: 1) aerial defaults 2) telescope defaults 3) plugin opitions 4) cmd options. This is …

feat: Adds syntax highlighting in the telescope picker

---

lua/aerial/backends/init.lua
lua/aerial/backends/lsp/init.lua

Fixes #393
Before closing a buffer all language servers are detached from it. This cause the `LspDetach` event to occur before the buffer is deleted and therefore is still valid. Part of the autocommand here when a language server detaches is it refreshes the symbols which is great when it is because a language server crashes or stopped by the user, but in the case of a buffer getting deleted is not the operation we really want to happen. It leads to a notification that no language servers are attached that support symbols. This is expected since the buffer has not been deleted yet (but will be immediately after)
It seems like this warning in `fetch_symbols` may not be necessary at all. There is a similar warning in the `is_supported` method of the LSP backend which I think covers the …

Fix warning when closing buffers with the LSP backend in place

---

README.md
queries/toml/aerial.scm
tests/symbols/toml_test.json
tests/treesitter/toml_test.toml

I wrote some queries for TOML.
Captures tables as "Class" and arrays of tables as "Enum".
```toml
[foo]
[foo.bar]
[[baz]]
[[baz]]
[[neo."vim"]]
[[neo."vim"]]
```
```
C foo
C foo.bar
E baz
E baz
E neo."vim"
E neo."vim"
```
Unfortunately, `[foo.bar]` is not actually a child of `[foo]` in the AST.
```scheme
(document
(table
(bare_key)) ; foo
(table
(dotted_key ; foo.bar
(bare_key) ; foo
(bare_key))) ; bar
(table_array_element
(bare_key)) ; baz
(table_array_element ; baz
(bare_key))
(table_array_element
(dotted_key ; neo."vim"
(bare_key) ; neo
(quoted_key))) ; "vim"
(table_array_element
(dotted_key ; neo."vim"
(bare_key)
(quoted_key))))
```
As a result, they are displayed as separate top level tables `foo` and `foo.bar`.
Would it be possible to neatly nest `bar` under `foo` using more complex …

feat(toml): treesitter support for TOML tables

---

README.md
lua/telescope/_extensions/aerial.lua

This PR adds a nesting symbol in telescope, and also makes the readme a bit clearer when using with telescope to prevent #373.
Closes #373

Allow nesting symbol to be used with telescope and fix docs

---

queries/php/aerial.scm

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 8:13. Invalid node type "anonymous_function_creation_expression":
right: (anonymous_function_creation_expression) @symbol)
^
stack traceback:
[C]: in function '_ts_parse_query'
/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
...y/aerial.nvim/lua/aerial/backends/treesitter/helpers.lua:43: in function 'get_query'
...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:19: in function 'is_supported'
...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:40: in function …
```

fix(php): anonymous_function_creation_expression replaced with anonymous_function

---

README.md
queries/just/aerial.scm
tests/minimal_init.lua
tests/symbols/just_test.json
tests/treesitter/just_test.just

This change adds treesitter query to support `just` filetype.
Ref: https://github.com/casey/just

feat(just): treesitter support for Just

---

README.md
lua/aerial/backends/treesitter/extensions.lua
queries/starlark/aerial.scm
tests/symbols/starlark_test.json
tests/treesitter/starlark_test.bazel

feat(starlark): treesitter support for Starlark
This is for generating symbol outline for Bazel BUILD files.

feat(starlark): treesitter support for Starlark

---

lua/aerial/backends/treesitter/init.lua
lua/telescope/_extensions/aerial.lua

Due to neovim's breaking change in treesitter, in nightly build the option all is set to true by default.
Closes #406

feat: explicitly set all to false in iter_matches

---

README.md
lua/telescope/_extensions/aerial.lua

the highlighting for the symbol type and the symbol name were lost with that change.
the telescope picker can be configured to display both symbol type and name and the line from the file.
#386 added highlighting for the line in the second part of the picker. however, doing so, it clobbered highlighting for the symbol type and name, which I am using thanks to the configurable `get_highlight` function to color differently public and private symbols.
this change makes sure the highlights for the first two columns are not clobbered by the line preview.
note, i'm not 100% sure about the offsets. i think there may be unicode widths shenanigans going on. but after this commit it's much better for sure.

fix telescope highlights regression from #386

---

queries/java/aerial.scm
tests/symbols/java_test.json
tests/treesitter/java_test.java

in the java tree-sitter hierarchy, annotations (`@Annotation`) before methods are nested within the `method_declaration`. In general they are indented on the line before the method itself (and sometimes there are many annotations, one per line, before the method).
The way aerial was capturing methods, in the telescope preview for instance, you'd see the annotation line instead of the method declaration line, and you were also taken to the "wrong" line.

java: don't start methods at annotations

---

lua/aerial/navigation.lua

This PR adds the ability to use the <C-o> and <C-i> bindings to jump back and forth after selecting something from the aerial menu. I've tested this locally and seems to work well.

Feature: Add to jumplist before jumping

---

queries/r/aerial.scm
tests/symbols/r_test.json
tests/treesitter/r_test.R

Adds support for R. Only adds one query for function definitions, but this is really all that's needed since R is a highly functional language.
I also added a test file `r_test.R`, but I wasn't able to get tests to run properly. Is there more to this than sourcing `tests/minimal_init.lua` and then using `:RunTests`?
Thanks!

feat: add queries for R

---

lua/aerial/navigation.lua

Calling a split-based action (e.g. aerial.action.jump_vsplit()) from a floating Aerial window triggers an error.
This happens because floating windows in Aerial are automatically closed via an autocmd when the window loses focus.
In `aerial.navigation.select_symbol()`, the split command doesn't disable these autocmds, so the floating window gets closed during the split. When the code attempts to return to the now-closed window, it raises an error.
Prefix the split command with `noautocmd` (`noau`) to prevent triggering the window-closing autocmd.
This aligns with the behavior of `aerial.util.go_win_no_au`, which also uses `noau` for safe window switching.

fix: prevent Aerial float window from closing on split (#456)

---

queries/latex/aerial.scm
tests/symbols/latex_test.json
tests/treesitter/latex_test.tex

Issue #459 highlights that the LaTeX Tree-sitter parser does not currently output \chapter sections.
Only \section, \subsection, and \subsubsection are supported by the parser at the moment.
According to [Overleaf’s documentation on sectioning](https://www.overleaf.com/learn/latex/Sections_and_chapters#Document_sectioning), \part and \chapter are additional valid sectioning levels. While \paragraph and \subparagraph are also described, they do not seem relevant to include here, in my opinion.
Changes made to address this issue:
* Add supports for \part and \chapter sections
* Add tests for \part and \chapter and update latex snapshot accordingly

fix(latex): update queries for latex treesitter parser (#459)

---

lua/aerial/snacks.lua

This modifies the `snacks.picker` integration to keep track of the last element of a parent and correctly sets the `last` field to `true`.
Before:
After:

fix: correctly set `last` property in `snack.picker` integration

---

lua/aerial/backends/lsp/init.lua

```
- WARNING client.request is deprecated. Feature will be removed in Nvim
0.13
- ADVICE:
- use client:request instead.
- stack traceback: */aerial.nvim/lua/aerial/backends/lsp/init.lua:39
*/aerial.nvim/lua/aerial/backends/init.lua:124
*/aerial.nvim/lua/aerial/backends/init.lua:149
*/aerial.nvim/lua/aerial/window.lua:335
*/aerial.nvim/lua/aerial/window.lua:373
*/aerial.nvim/lua/aerial/init.lua:304
*/aerial.nvim/lua/aerial/command.lua:8
```

fix: elimante deprecated warings on nightly

---

README.md
doc/aerial.txt
doc/api.md
lua/aerial/fzf-lua.lua
lua/aerial/init.lua

This adds a picker for https://github.com/ibhagwan/fzf-lua/
It supports multi-select and uses the default actions from the `files` picker (e.g. `<C-s>` to open a symbol in a split).
Adapted from the snacks picker.

feat: add fzf-lua symbol picker

---

lua/aerial/backends/lsp/init.lua

This fixes the request function in Neovim <0.11 with a missing `return` making it seem like all requests are failing.

fix: missing `return` in `request` call for Neovim <0.11

---

queries/yaml/aerial.scm
tests/symbols/yaml_test2.json
tests/treesitter/yaml_test2.yml

Previously, these elements were not listed as symbols. redhat's yaml-language-server lists these as numbered elements such as 0, 1, 2, but treesitter strategy didn't match them at all.
There's a de-facto standard for many yaml formats, to use the "name" key to solve this problem. It is a best practice for commonly used yaml files such as github workflows and ansible.
Note: I can tune the query if there are concerns: I'm aware this looks a bit strange, but it really makes these files possible to navigate, and doesn't hurt anything else (only introduces symbol where one didn't exist before). Try it out on some actions/ansible files.

feat(yaml): treesitter name array elements symbol based upon "name" key
